project:
  type: website
  output-dir: _site
  resources:
    - images/**
resource-path:
  - images
  - .

website:
  title: "PraxisAustausch"
  site-url: https://OGERHub.github.io/praxis-austausch
  repo-url: https://github.com/OGERHub/praxis-austausch
  repo-actions: []   # [source, issue, edit] bei Bedarf manuell setzen
  page-navigation: true
  bread-crumbs: false
  open-graph: true
  image: images/banner.png
  page-footer:
    center: |
      Didaktik der Physischen Geographie (<span class="year"></span>) —
      <a class="impressum-link" href="base/impressum.html">Impressum</a>

  search:
    location: navbar
    type: textbox

  navbar:
    background: primary
    foreground: light
    logo: images/your-logo.png
    left:
      - icon: question-square-fill
        text: FAQ
        href: base/faq.qmd
    right:
      - icon: chat-left-text-fill
        text: "ILIAS"
        href: "https://www.ilias.uni-koeln.de/ilias/login.php?client_id=uk&cmd=force_login&lang=de"

  sidebar:
    pinned: true
    align: center
    style: docked
    collapse-level: 1
    contents:
      - section: "Willkommen"
        contents:
          - index.qmd
          - base/about.qmd
      - text: "---"
      - section: "Kurs-Sitzungen"
        contents:
              - session-2/sitzung-2-intro.qmd
              - session-2/sitzung-2-gierig.qmd
              - session-2/sitzung-2-nachhaltig.qmd
              - session-2/sitzung-2-klimagerechtigkeit.qmd

format:
  html:
    theme:
      light: [lumen]

    css: css/styles.css
    toc: true
    code-copy: true
    code-background: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)//(OGERHub\.github\.io/praxis\-austausch|www\.quarto\.org/custom)'
    md-extensions: +fenced_divs+bracketed_spans+link_attributes
    include-after-body:
      - "includes/_footer-year.html"


lang: de
